### ISSUE TITLE
Cumulus ignores fake locations

### ISSUE THREAD

**Issue by matc17** [kflog-project/Cumulus#114]
I use X-Plane to GPS (https://play.google.com/store/apps/details?id=com.appropel.xplanegps&hl=de) often in order to learn using navigation software of the ground in a simulator rather than using up brain capacity for that in the air.
However Cumulus just ignores the fake location, and only uses the built-in GPS directly

**Comment by speed-axel** [comment]
Due to no more support for Android releases > 6 that issue is not more valid and will be closed.
