### ISSUE TITLE
Cumulus crashes under Android, if the volume up or down key is pressed

### ISSUE THREAD

**Issue by speed-axel** [kflog-project/Cumulus#115]
Cumulus crashes under Android, if the volume up or down key is pressed.

**Comment by speed-axel** [comment]
The volume up or down key is mapped by Cumulus as zoom in/out.

**Comment by eehmke** [comment]
Am Montag, 10. April 2017, 12:44:25 CEST schrieb Axel Pauli:
> The volume up or down key is mapped by Cumulus as zoom in/out.
Yes. But it crashes anyway.

Cheers, Eggert

**Comment by speed-axel** [comment]
Hi Eggert,

I'm just preparing a new delivery. Be patient. The new release is on the way.
