### ISSUE TITLE
consider 8.33 KHz new radio channel distance

### ISSUE THREAD

**Issue by speed-axel** [kflog-project/Cumulus#119]
Radio frequencies should not more displayed with the unit MHz. Instead of the word frequency the term channel should be used because the 8.33 KHz radios show only channels and the channels are not more identical with the used working frequency.

**Comment by matc17** [comment]
What do you mean by channels? My Drittel krt2 also shows a frequency in
8.33 Mode... Or did I get something wrong?

Am 13.01.2018 6:17 nachm. schrieb "Axel Pauli" <notifications@github.com>:

**Comment by speed-axel** [comment]
The KRT2 Radio has in its user guide Section 8.1 a Frequency Channel Plan. In Channel raster 25KHz is the displayed frequency the same as the used working frequency by the radio. In channel raster 8.33KHz the displayed frequency by the radio is another as the working frequency.

Example:

118.0083 MHz working frequency is displayed as 118.005. Therefore both are not more equal. The displayed value 118.005 is named a channel.
